### ISSUE TITLE
Привет! Очень нужна ваша помощь.

### ISSUE THREAD

**Issue by seberia** [DenisDubinin1973/YandexPracticumQA2022#1]
По сложившимся обстоятельствам не успеваю доделать диплом, попросту нет времени им заниматься. Если есть такая возможность, можете сделать ваши баг репорты в текстовом виде как в 4 спринте было?

**Comment by DenisDubinin1973** [comment]
Напишите мне в телеграмме, могу наскриншотить репорты.

**Comment by seberia** [comment]
Можно ссылку на телеграмм

**Comment by DenisDubinin1973** [comment]
На гитхабе есть.  И там 3 десятка репортов и все со скриншотами и /или видео.  Скриншоты и видео придется делать самостоятельно.

**Comment by DenisDubinin1973** [comment]
Fixed
